# https://google.github.io/adk-docs/integrations/bigquery-agent-analytics/#use-with-agent

# my_bq_agent/agent.py
import os
import google.auth
from google.adk.apps import App
from google.adk.plugins.bigquery_agent_analytics_plugin import BigQueryAgentAnalyticsPlugin, BigQueryLoggerConfig
from google.adk.agents import Agent
from google.adk.models.google_llm import Gemini
from google.adk.tools.bigquery import BigQueryToolset, BigQueryCredentialsConfig


### Commented out original code from https://google.github.io/adk-docs/integrations/bigquery-agent-analytics/#use-with-agent to enable cloud logging into Observability Analytics

## --- OpenTelemetry TracerProvider Setup (Optional) ---
## ADK includes OpenTelemetry as a core dependency.
## Configuring a TracerProvider enables full distributed tracing
## (populates trace_id, span_id with standard OTel identifiers).
## If no TracerProvider is configured, the plugin falls back to internal
## UUIDs for span correlation while still preserving the parent-child hierarchy.
# from opentelemetry import trace
# from opentelemetry.sdk.trace import TracerProvider
# trace.set_tracer_provider(TracerProvider())


## Comments below generated by Claude Opus 4.6
# --- Cloud Trace Setup ---
# Do NOT configure a TracerProvider manually here.
# The ADK web server sets its own TracerProvider at startup, and OpenTelemetry
# forbids overriding it ("Overriding of current TracerProvider is not allowed").
#
# Instead, use the built-in CLI flags when starting the local dev server:
#
#   adk web --trace_to_cloud .          # adds CloudTraceSpanExporter
#   adk web --otel_to_cloud .           # Cloud Trace + Cloud Logging + GenAI instrumentation
#
# Prerequisites:
#   1. Enable Cloud Trace API:
#      gcloud services enable cloudtrace.googleapis.com --project "$GOOGLE_CLOUD_PROJECT"
#   2. Authenticate locally:
#      gcloud auth application-default login
#   3. The authenticated principal needs roles/cloudtrace.agent (or equivalent).

# --- Configuration ---
PROJECT_ID = os.environ.get("GOOGLE_CLOUD_PROJECT", "your-gcp-project-id")
DATASET_ID = os.environ.get("BIG_QUERY_DATASET_ID", "your-big-query-dataset-id")
LOCATION = os.environ.get("GOOGLE_CLOUD_LOCATION", "US")
GCS_BUCKET = os.environ.get("GCS_BUCKET", "your-gcs-bucket") # Optional

if PROJECT_ID == "your-gcp-project-id":
    raise ValueError("Please set GOOGLE_CLOUD_PROJECT or update the code.")

# --- CRITICAL: Set environment variables BEFORE Gemini instantiation ---
os.environ['GOOGLE_CLOUD_PROJECT'] = PROJECT_ID
os.environ['GOOGLE_CLOUD_LOCATION'] = LOCATION
os.environ['GOOGLE_GENAI_USE_VERTEXAI'] = 'True'


# --- Initialize the BQ Agent Analytics Plugin ---
bq_config = BigQueryLoggerConfig(
    enabled=True,
    gcs_bucket_name=GCS_BUCKET, # Enable GCS offloading for multimodal content
    log_multi_modal_content=True,
    max_content_length=500 * 1024, # 500 KB limit for inline text
    batch_size=1, # Default is 1 for low latency, increase for high throughput
    shutdown_timeout=10.0
)

bq_agent_analytics_plugin = BigQueryAgentAnalyticsPlugin(
    project_id=PROJECT_ID,
    dataset_id=DATASET_ID,
    table_id="agent_events",
    config=bq_config,
    location=LOCATION
)

# --- Initialize BigQuery Toolset ---
credentials, _ = google.auth.default(scopes=["https://www.googleapis.com/auth/cloud-platform"])
bigquery_toolset = BigQueryToolset(
    credentials_config=BigQueryCredentialsConfig(credentials=credentials)
)

llm = Gemini(model="gemini-2.5-flash")

root_agent = Agent(
    name='my_bq_agent',
    model=llm,
    instruction="You are a helpful assistant with access to BigQuery tools.",
    tools=[bigquery_toolset]
)

# --- Create the App ---
app = App(
    name="my_bq_agent",
    root_agent=root_agent,
    plugins=[bq_agent_analytics_plugin],
)
